- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-080e50b9c818a24d5
    ami_id: ami-0220d79f3f480ecf5
    domain_name: mskdaws88s.online
    env: dev
    instances:
    - mongodb
    - catalogue 
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Nmae: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
    
  - name: print the output  
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}" #monogodb-env.mskdaws88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "roboshop-{{ env }}.{{ domain_name }}" #roboshop-env.mskdaws88s.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    when: item.item == "frontend"